version: '3'

services:
  app:
    build: .
    ports:
      - '4200:4200'
    command: yarn typeorm migration:run && yarn start:dev
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - api
  postgres:
    image: postgres:11.6-alpine
    environment:
      POSTGRES_PASSWORD: 'masterkey'
    ports:
      - '5435:5432'
    volumes:
      - ./Postgre11SQLData:/var/lib/postgresql/data
    networks:
      - api
    restart: always

networks:
  api:
